POST http://nvrtx.oslomet.no:8001/drf1/zone/
Content-Type: application/json
Cookie: key=first-value

{
  "lettername": "zone3",
  "sequencenumber": 3,
  "description": "printerrom",
  "comment": "printerrom",
  "activity": [
    {
      "code": "grudig",
      "startTime": "2022-03-10T13:17:27.853707Z",
      "numberOfVisitors": "1",
      "countingUser":"1"
    }
  ]
}

###