# Generated by Django 4.0.3 on 2022-03-10 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettername', models.CharField(max_length=50)),
                ('sequencenumber', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('countingUser', models.IntegerField()),
                ('numberOfVisitors', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf1.activity')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf1.zone')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='zone',
            field=models.ManyToManyField(through='drf1.ActivityZone', to='drf1.zone'),
        ),
    ]
