# Generated by Django 4.0.3 on 2022-03-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='zone',
        ),
        migrations.AddField(
            model_name='zone',
            name='activity',
            field=models.ManyToManyField(through='drf1.ActivityZone', to='drf1.activity'),
        ),
    ]
