# Generated by Django 4.0.3 on 2022-03-26 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(blank=True)),
                ('countingUser', models.IntegerField(default=0)),
                ('numberOfVisitors', models.IntegerField(default=-1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf2.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettername', models.CharField(max_length=50)),
                ('sequencenumber', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('observerName', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('activity', models.ManyToManyField(through='drf2.ActivityZone', to='drf2.activity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf2.project')),
            ],
            options={
                'unique_together': {('lettername', 'sequencenumber', 'project')},
            },
        ),
        migrations.CreateModel(
            name='Counting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observerName', models.CharField(blank=True, default='', max_length=50)),
                ('startTime', models.DateTimeField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf2.project')),
            ],
        ),
        migrations.AddField(
            model_name='activityzone',
            name='counting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drf2.counting'),
        ),
        migrations.AddField(
            model_name='activityzone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf2.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='activityzone',
            unique_together={('activity', 'zone')},
        ),
    ]
