# Generated by Django 4.0.3 on 2022-03-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='observerName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='zone',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='activityzone',
            unique_together={('activity', 'zone')},
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('lettername', 'sequencenumber', 'project')},
        ),
    ]
