# Generated by Django 4.0.3 on 2022-03-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityzone',
            name='startTime',
        ),
    ]
