# Generated by Django 4.0.3 on 2022-03-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf2', '0002_zone_observername_alter_zone_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='observerName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
