# Generated by Django 4.0.3 on 2022-04-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf2', '0003_alter_counting_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activities',
            field=models.ManyToManyField(blank='True', to='drf2.activity'),
        ),
    ]
