# Generated by Django 4.0.3 on 2022-03-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf2', '0004_alter_zone_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='observerName',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
