# Generated by Django 4.0.3 on 2022-03-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf2', '0005_alter_zone_comment_alter_zone_observername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='zone',
            name='observerName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
