# Generated by Django 4.0.3 on 2022-04-06 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf2', '0005_alter_zone_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='activity',
            new_name='activities',
        ),
        migrations.AlterField(
            model_name='zone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='drf2.project'),
        ),
    ]
