# Generated by Django 4.0.3 on 2022-03-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf2', '0006_alter_zone_comment_alter_zone_observername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
