# Generated by Django 4.0.3 on 2022-04-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf2', '0006_rename_activity_zone_activities_alter_zone_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityzone',
            unique_together={('activity', 'zone', 'counting')},
        ),
    ]
