# Generated by Django 4.0.3 on 2022-03-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf2', '0007_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityzone',
            name='countingUser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activityzone',
            name='numberOfVisitors',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='activityzone',
            name='startTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
