# Generated by Django 4.0.3 on 2022-06-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf2', '0008_observer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observers', to='drf2.project'),
        ),
    ]
